# Generated by Django 5.1.7 on 2025-04-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='users.patient'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='equipment.commande'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='users.vendeur'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.materiel'),
        ),
    ]
