# Generated by Django 5.1.7 on 2025-04-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_destinataire', models.CharField(choices=[('KINE', 'Kinésithérapeute'), ('VENDEUR', 'Vendeur')], default='KINE', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField(auto_now_add=True)),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours de traitement'), ('RESOLUE', 'Résolue'), ('FERMEE', 'Fermée')], default='NOUVELLE', max_length=20)),
                ('reponse', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'ordering': ['-date', '-heure'],
            },
        ),
    ]
